// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.3
// source: v1/coauth.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientName    string                 `protobuf:"bytes,1,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	HomePage      string                 `protobuf:"bytes,2,opt,name=home_page,json=homePage,proto3" json:"home_page,omitempty"`
	ClientSummary string                 `protobuf:"bytes,3,opt,name=client_summary,json=clientSummary,proto3" json:"client_summary,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,4,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	Scopes        []string               `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	UserId        string                 `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppRequest) Reset() {
	*x = AddAppRequest{}
	mi := &file_v1_coauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppRequest) ProtoMessage() {}

func (x *AddAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_coauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppRequest.ProtoReflect.Descriptor instead.
func (*AddAppRequest) Descriptor() ([]byte, []int) {
	return file_v1_coauth_proto_rawDescGZIP(), []int{0}
}

func (x *AddAppRequest) GetClientName() string {
	if x != nil {
		return x.ClientName
	}
	return ""
}

func (x *AddAppRequest) GetHomePage() string {
	if x != nil {
		return x.HomePage
	}
	return ""
}

func (x *AddAppRequest) GetClientSummary() string {
	if x != nil {
		return x.ClientSummary
	}
	return ""
}

func (x *AddAppRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

func (x *AddAppRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AddAppRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AddAppReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAppReply) Reset() {
	*x = AddAppReply{}
	mi := &file_v1_coauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAppReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppReply) ProtoMessage() {}

func (x *AddAppReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_coauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppReply.ProtoReflect.Descriptor instead.
func (*AddAppReply) Descriptor() ([]byte, []int) {
	return file_v1_coauth_proto_rawDescGZIP(), []int{1}
}

func (x *AddAppReply) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddAppReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddAppReply) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	ResponseType  string                 `protobuf:"bytes,3,opt,name=response_type,json=responseType,proto3" json:"response_type,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_v1_coauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_coauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_v1_coauth_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthorizeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *AuthorizeRequest) GetResponseType() string {
	if x != nil {
		return x.ResponseType
	}
	return ""
}

func (x *AuthorizeRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type AuthorizeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeReply) Reset() {
	*x = AuthorizeReply{}
	mi := &file_v1_coauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeReply) ProtoMessage() {}

func (x *AuthorizeReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_coauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeReply.ProtoReflect.Descriptor instead.
func (*AuthorizeReply) Descriptor() ([]byte, []int) {
	return file_v1_coauth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *AuthorizeReply) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AuthorizeReply) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	GrantType     string                 `protobuf:"bytes,3,opt,name=grant_type,json=grantType,proto3" json:"grant_type,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,5,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	DataType      string                 `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Callback      string                 `protobuf:"bytes,7,opt,name=callback,proto3" json:"callback,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,8,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_v1_coauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_coauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_v1_coauth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *TokenRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

func (x *TokenRequest) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *TokenRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *TokenRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *TokenRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *TokenRequest) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *TokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type TokenReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenReply) Reset() {
	*x = TokenReply{}
	mi := &file_v1_coauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenReply) ProtoMessage() {}

func (x *TokenReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_coauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenReply.ProtoReflect.Descriptor instead.
func (*TokenReply) Descriptor() ([]byte, []int) {
	return file_v1_coauth_proto_rawDescGZIP(), []int{5}
}

func (x *TokenReply) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenReply) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *TokenReply) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

func (x *TokenReply) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

var File_v1_coauth_proto protoreflect.FileDescriptor

const file_v1_coauth_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/coauth.proto\x12\rapi.coauth.v1\x1a\x1cgoogle/api/annotations.proto\"\xc8\x01\n" +
	"\rAddAppRequest\x12\x1f\n" +
	"\vclient_name\x18\x01 \x01(\tR\n" +
	"clientName\x12\x1b\n" +
	"\thome_page\x18\x02 \x01(\tR\bhomePage\x12%\n" +
	"\x0eclient_summary\x18\x03 \x01(\tR\rclientSummary\x12!\n" +
	"\fcallback_url\x18\x04 \x01(\tR\vcallbackUrl\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\"X\n" +
	"\vAddAppReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\"\x8d\x01\n" +
	"\x10AuthorizeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12#\n" +
	"\rresponse_type\x18\x03 \x01(\tR\fresponseType\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"]\n" +
	"\x0eAuthorizeReply\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\"\x84\x02\n" +
	"\fTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\x12\x1d\n" +
	"\n" +
	"grant_type\x18\x03 \x01(\tR\tgrantType\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12!\n" +
	"\fredirect_uri\x18\x05 \x01(\tR\vredirectUri\x12\x1b\n" +
	"\tdata_type\x18\x06 \x01(\tR\bdataType\x12\x1a\n" +
	"\bcallback\x18\a \x01(\tR\bcallback\x12#\n" +
	"\rrefresh_token\x18\b \x01(\tR\frefreshToken\"\x92\x01\n" +
	"\n" +
	"TokenReply\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken2\x9c\x02\n" +
	"\x06coauth\x12b\n" +
	"\tAuthorize\x12\x1f.api.coauth.v1.AuthorizeRequest\x1a\x1d.api.coauth.v1.AuthorizeReply\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/authorize\x12U\n" +
	"\x05Token\x12\x1b.api.coauth.v1.TokenRequest\x1a\x19.api.coauth.v1.TokenReply\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/token\x12W\n" +
	"\x06AddApp\x12\x1c.api.coauth.v1.AddAppRequest\x1a\x1a.api.coauth.v1.AddAppReply\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/appsB#\n" +
	"\rapi.coauth.v1P\x01Z\x10coauth/api/v1;v1b\x06proto3"

var (
	file_v1_coauth_proto_rawDescOnce sync.Once
	file_v1_coauth_proto_rawDescData []byte
)

func file_v1_coauth_proto_rawDescGZIP() []byte {
	file_v1_coauth_proto_rawDescOnce.Do(func() {
		file_v1_coauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_coauth_proto_rawDesc), len(file_v1_coauth_proto_rawDesc)))
	})
	return file_v1_coauth_proto_rawDescData
}

var file_v1_coauth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_v1_coauth_proto_goTypes = []any{
	(*AddAppRequest)(nil),    // 0: api.coauth.v1.AddAppRequest
	(*AddAppReply)(nil),      // 1: api.coauth.v1.AddAppReply
	(*AuthorizeRequest)(nil), // 2: api.coauth.v1.AuthorizeRequest
	(*AuthorizeReply)(nil),   // 3: api.coauth.v1.AuthorizeReply
	(*TokenRequest)(nil),     // 4: api.coauth.v1.TokenRequest
	(*TokenReply)(nil),       // 5: api.coauth.v1.TokenReply
}
var file_v1_coauth_proto_depIdxs = []int32{
	2, // 0: api.coauth.v1.coauth.Authorize:input_type -> api.coauth.v1.AuthorizeRequest
	4, // 1: api.coauth.v1.coauth.Token:input_type -> api.coauth.v1.TokenRequest
	0, // 2: api.coauth.v1.coauth.AddApp:input_type -> api.coauth.v1.AddAppRequest
	3, // 3: api.coauth.v1.coauth.Authorize:output_type -> api.coauth.v1.AuthorizeReply
	5, // 4: api.coauth.v1.coauth.Token:output_type -> api.coauth.v1.TokenReply
	1, // 5: api.coauth.v1.coauth.AddApp:output_type -> api.coauth.v1.AddAppReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_v1_coauth_proto_init() }
func file_v1_coauth_proto_init() {
	if File_v1_coauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_coauth_proto_rawDesc), len(file_v1_coauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_coauth_proto_goTypes,
		DependencyIndexes: file_v1_coauth_proto_depIdxs,
		MessageInfos:      file_v1_coauth_proto_msgTypes,
	}.Build()
	File_v1_coauth_proto = out.File
	file_v1_coauth_proto_goTypes = nil
	file_v1_coauth_proto_depIdxs = nil
}
